version: 2

defaults: &defaults

  resource_class: large

  docker:
    - image: koding/circle@sha256:33519ba755fd1a436e7891782a65b1d99b02fafebc104bd0e8ed9bc5e83d3e71

  working_directory: /koding

workflows:

  version: 2

  default:

    jobs:

jobs:
